name: Action Runner
on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: '*/20 * * * *' # Runs every 20 minutes (UTC)
concurrency: 
  group:  ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
    build:
      timeout-minutes: 14400      # let the job running 10 days..
      name: Update Action Runner Status
      runs-on: [Windows, x64, Self-hosted]
      steps:
        - name: check repo content
          uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v5
          with:
            python-version: '3.9'
            cache: 'pip' # caching pip dependencies
        - run: pip install -r requirements.txt
        - name: python runner-status.py
          env:
            ENDPOINT1_HEADER_TOKEN: ${{ secrets.ENDPOINT1_HEADER_TOKEN }}
            ENDPOINT2_HEADER_TOKEN: ${{ secrets.ENDPOINT2_HEADER_TOKEN }}
            GDRIVE_API_CREDENTIALS: ${{ secrets.GDRIVE_API_CREDENTIALS }}
          run: python runner-status.py