name: Powershell
on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: '0 12 * * 1' # Runs every Monday at noon (UTC)
jobs:
    build:
      name: Run Script
      runs-on: [Windows, x64, Self-hosted]
      steps:
        - uses: actions/checkout@v2
        - name: Script
          run: .\script.ps1
          shell: powershell
