name: Windows PowerShell
on:
  schedule:
    - cron: '0 12 * * 1' # Runs every Monday at noon (UTC)

jobs:
    build:
      name: Run Script
      runs-on: [Windows, x64, Self-hosted]
      steps:
        - uses: actions/checkout@v1
        - name: Script
          run: .\script.ps1
          shell: powershell
